-- Clear all existing data and re-import from Excel
DELETE FROM payments;
DELETE FROM attendance;
DELETE FROM whatsapp_logs;
DELETE FROM students;

DO $$
DECLARE
  sid uuid;
BEGIN
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Aryan Dnyanoba Narle+tupe', '10th', 'English', 5000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 1000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('VaibhavManik jadhav', '10th', 'English', 16000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 1000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Ayush Hanumant wanjale', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Rohit Santosh ambekar', '10th', 'English', 16000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Shivraj Santosh Surve', '10th', 'English', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Om Gulab Thakur', '10th', 'Marathi', 15000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 1500.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Vaishnavi Gopal Ambekar', '10th', 'English', 16000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Anushka Bharat Nanavre', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 1600.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 1600.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4800.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 1600.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6400.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Arti Dhananjay Holle', '10th', 'English', 16000.0, 'inactive', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Prathmesh Pramod Gundre', '10th', 'English', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Balaji Biradar', '10th', 'Marathi', 16000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Waroop Satish Patil', '10th', 'English', 17000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 17000.0, 'cash', 'Instalment 1');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Tahsin Khan', '10th', 'English', 31000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 21000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 1000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Om Jogdand', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Shravan Barge', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 7000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Kartik Kudhale', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Shubham Kiran Avhad', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Saish Sandip Gaikwad', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Arya Naidu', '10th', 'English', 10000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Pavan Panpatte', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Arjun Taware', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Samarth Ghorse', '10th', 'English', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('samarth aakash kokane', '10th', 'English', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Prathamesh Patil', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Suraj kale', '10th', 'Marathi', 15000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Siddharth Shriram Barge', '10th', 'Marathi', 15000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Yash Dhananjay Holle', '10th', 'Marathi', 15000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Rampure', '10th', 'Marathi', 10000.0, 'inactive', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Aditi Sanjay Ambekar', '10th', 'CBSE', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Aadya khule', '10th', 'CBSE', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Disha Sonawane', '10th', 'CBSE', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Vivan Agale', '10th', 'CBSE', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Mohak khule', '4th', 'CBSE', 6000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Aarohi Dattatrey Mhala', '4th', 'CBSE', 6000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Fatima Khan', '4th', 'CBSE', 6000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Ishaan Rajesh Lele', '5th', 'CBSE', 6000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Aura Dattatrey Mhala', '6th', 'CBSE', 6000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Atharv Agale', '7th', 'CBSE', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Arnav Narle', '7th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Sejal Borude', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Hitesh Manoj Shringare', '8th', 'CBSE', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Parth Dnyanoba narle', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Aarya Mhala', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Tanmay Rajmane', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Atharv Ashish Goskhe', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 8000.0, 'cash', 'Instalment 1');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Prathmesh Paresh Patil', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Vedant Wagh', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Janhavi Sandeep Katole', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Diksha Satish Magar', '8th', 'Marathi', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Prathvi Naidu', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Vivaan Aakash kokane', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Aradhya Avinash Goskhe', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Pratham Jitendra giri', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 8000.0, 'cash', 'Instalment 1');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Dip jagtap', '8th', 'English', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Aryan Ganesh Goskhe', '9th', 'English', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 12000.0, 'cash', 'Instalment 1');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Asmita Kailas Surve', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('vedant popat', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Saish Sanjay Avhad', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Praful popat', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Sibtan Khan', '9th', 'CBSE', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('saish barge', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('swarup mhatre', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Kaustubh rajmane', '12th', 'SSC', 25000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Neel kudale', 'Other', 'SSC', 20000.0, 'inactive', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Arohi Rajmane', 'Other', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('arnav patil', 'Other', 'SSC', 6000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
END;
$$;