DO $$
DECLARE
  sid uuid;
BEGIN
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Laksh K Rajpurohit', '9th', 'CBSE', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Shubham Vishwakarma', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Samrudhi sanjay varak', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Swaraj kadam', '9th', 'CBSE', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Sivam Singh', '9th', 'CBSE', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Arnav Shrikant Nalgude', '9th', 'English', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Mayank Sandip Khilare', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Daksh Kshirsagar', '9th', 'CBSE', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Ravi Gupta', '9th', 'CBSE', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Anshika Vishwakarma', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Arushi Gupta', '9th', 'CBSE', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Bhati Kishan', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Shejal Jadhav', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Nilesh Khushwaha', '9th', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Harshita,Saee,Swaraj', '9th', 'CBSE', 36000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 18000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 18000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('sai pardeshi', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('prutvi patil', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Vaisnavi Sanjay Wadekar', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Jahnavi Pradeep Chavhan', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Purvi Amar Vasve', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Sidhi Dhanraj Shirke', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Samiksha Rahul Sanar', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Rupali Suresh Kharat', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Sohan Navnath varhade', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Chandraprakash k Rajpurohit', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Shlok Pasalkar', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Abhay more', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Sanket Mahatne', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Saunak Joshi', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Soham Sachin Bechavde', '12th', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Devkule Tanuja', 'Other', 'SSC', 20000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Shreya Mare', 'Other', 'SSC', 15000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Bhakti Hasariya', 'Other', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Maitrika patil', 'Other', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Manisha jogdand', 'Other', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Vedant Mahajan', 'Other', 'SSC', 12000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
END;
$$;