DO $$
DECLARE
  sid uuid;
BEGIN
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Vaishnavi Mule', '10th', 'English', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 8000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Rupali Suryavanshi', '10th', 'English', 16000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Sharvari Maral', '10th', 'English', 16000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 7000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('sunaina saroj', '10th', 'English', 15000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Shantanu Phale', '10th', 'English', 16000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('samarth mokar. Cbse', '10th', 'CBSE', 30000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Harshvardhan dangat', '10th', 'CBSE', 30000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Swarali kadam', '10th', 'CBSE', 30000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 20000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('saurav raut', '10th', 'SSC', 30000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 9000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('sanas mayur', '10th', 'SSC', 30000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('chavhan Samrudhi', '10th', 'SSC', 17000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 4');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('vedant rawade', '10th', 'SSC', 18000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 7000.0, 'cash', 'Instalment 3');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Chaitna ghadshi', '10th', 'SSC', 16000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('om kamble', '10th', 'SSC', 25000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 5');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 6');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Adarsh Panchal', '10th', 'SSC', 15000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 6000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 1000.0, 'cash', 'Instalment 5');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('pranjal kalshettiy', '10th', 'SSC', 25000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 10000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 2');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 3');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 3000.0, 'cash', 'Instalment 4');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 2000.0, 'cash', 'Instalment 5');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 6');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Renu pawar', '10th', 'SSC', 15000.0, 'inactive', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 5000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('harshal', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('tushar', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('ganesh', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('niranjan', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('sarthak', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Dipika', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('veer kambale', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('sarthak varak', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('Ambure', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
  INSERT INTO students (name, class, medium, total_fees, status, mobile, batch, subjects, lecture_days, discount, fee_due_day) VALUES ('kaustubh thakar', '8th', 'SSC', 8000.0, 'active', '0000000000', 'morning', '{}', '{}', 0, 1) RETURNING id INTO sid;
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 1');
  INSERT INTO payments (student_id, amount, payment_mode, notes) VALUES (sid, 4000.0, 'cash', 'Instalment 2');
END;
$$;